### ISSUE TITLE
Using an existing remote MongoDB installation

### ISSUE THREAD

**Issue by scottpendlebury** [s-tip/stip-common#118]
Hi, is there a single place where I can configure S-TIP to use an existing remote installation of MongoDB? I have seen that there are numerous places where a MongoDB install can be set:

1. https://github.com/s-tip/stip-txs2/blob/010fb1af9041eae98ea5e8e6651f2e47d493ce5d/src/core/boot.py
2. https://github.com/s-tip/stip-rs/blob/dde71ee13d5d9e4065fe9b1444b5051cfb6cf4a0/src/ctirs/models/sns/config/models.py
3. https://github.com/s-tip/stip-rs/blob/dde71ee13d5d9e4065fe9b1444b5051cfb6cf4a0/src/ctirs/models/sns/config/fixture/sns_config.json

Is there a place where this configuration can be overwritten to not use a local install of MongoDB by default?

Thanks

**Comment by stmtstk** [comment]
@scottpendlebury 

Thank you for reaching us.

> Is there a place where this configuration can be overwritten to not use a local install of MongoDB by default?

Unfortunately S-TIP currently only supports MongoDB on localhost.

If you will use remote MongoDB instead of localhost, you have to modify the source codes that you mentioned as No.1 and No.2 (You don't have to modify `sns_config.json` as No.3).

Additionally, if you will use TAXII Server 2.1, you will have to also modify the source code below.

https://github.com/s-tip/stip-txs2/blob/46c510f352c5fa3c90f9c7714081de24a15370c4/src/core/boot.py#L16

After modify the source codes, please reboot Apache2.

Thanks.

**Comment by scottpendlebury** [comment]
Hi @stmtstk, many thanks for the prompt response and for the clear solution - much appreciated 😃.
